/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package incidents.ui;

import incidents.service.IncidentService;
import incidents.entites.Incident;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import incidents.service.EquipementService;
import incidents.service.TechnicienService;
import incidents.entites.Equipement;
import incidents.entites.Technicien;
import javax.swing.JOptionPane;

public class Incidentui extends javax.swing.JInternalFrame {
private IncidentService is = new IncidentService();
private EquipementService es = new EquipementService();
private TechnicienService ts = new TechnicienService();
private DefaultTableModel model;
    /**
     * Creates new form Incident
     */
    public Incidentui() {
        initComponents();
        model = (DefaultTableModel) Incidents.getModel();

    // Remplir les combobox
    cmbPriorite.addItem("Haute");
    cmbPriorite.addItem("Moyenne");
    cmbPriorite.addItem("Basse");
    
    cmbStatut.addItem("Ouvert");
    cmbStatut.addItem("En cours");
    cmbStatut.addItem("Cloture");
    
    loadData();
    loadEquipement();
    loadTechnicien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateOuvertureChooser = new com.toedter.calendar.JDateChooser();
        dateClotureChooser = new com.toedter.calendar.JDateChooser();
        cmbPriorite = new javax.swing.JComboBox();
        cmbStatut = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEquipement = new javax.swing.JComboBox();
        cmbTechnicien = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Incidents = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Les informations des incidents"));

        jLabel1.setText("Date d'ouverture:");

        jLabel2.setText("Date Cloture:");

        jLabel3.setText("Priorite:");

        jLabel4.setText("Statut:");

        cmbPriorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrioriteActionPerformed(evt);
            }
        });

        cmbStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatutActionPerformed(evt);
            }
        });

        jLabel5.setText("Equipement :");

        jLabel6.setText("Technicien :");

        cmbEquipement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipementActionPerformed(evt);
            }
        });

        cmbTechnicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTechnicienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPriorite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbStatut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateClotureChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(dateOuvertureChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEquipement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTechnicien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dateOuvertureChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dateClotureChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPriorite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbEquipement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbTechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        btnAjouter.setText("Ajouter");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier)
                    .addComponent(btnAjouter))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAjouter)
                .addGap(84, 84, 84)
                .addComponent(btnModifier)
                .addGap(88, 88, 88)
                .addComponent(btnSupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des incidents"));

        Incidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Date Ouverture", "Date Cloture", "Priorite", "Statut", "Equipement", "Technicien"
            }
        ));
        Incidents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncidentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Incidents);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed

    // Vérification des champs
    if (dateOuvertureChooser.getDate() == null ||
        cmbPriorite.getSelectedItem() == null ||
        cmbStatut.getSelectedItem() == null ||
        cmbEquipement.getSelectedItem() == null ||
        cmbTechnicien.getSelectedItem() == null) {

        JOptionPane.showMessageDialog(this,
                "Veuillez remplir tous les champs !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    Incident i = new Incident();
    i.setDateOuverture(dateOuvertureChooser.getDate());
    i.setDateCloture(dateClotureChooser.getDate());
    i.setPriorite(cmbPriorite.getSelectedItem().toString());
    i.setStatut(cmbStatut.getSelectedItem().toString());

    Equipement e = (Equipement) cmbEquipement.getSelectedItem();
    Technicien t = (Technicien) cmbTechnicien.getSelectedItem();

    i.setEquipement(e);
    i.setTechnicien(t);

    if (is.create(i)) {
        JOptionPane.showMessageDialog(this,
                "Incident ajouté avec succès !");
        loadData();
    } else {
        JOptionPane.showMessageDialog(this,
                "Erreur lors de l'ajout !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnAjouterActionPerformed
    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed


    int row = Incidents.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un incident à modifier !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (dateOuvertureChooser.getDate() == null) {
        JOptionPane.showMessageDialog(this,
                "La date d'ouverture est obligatoire !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    int id = Integer.parseInt(model.getValueAt(row, 0).toString());

    Incident i = new Incident();
    i.setIdIncident(id);
    i.setDateOuverture(dateOuvertureChooser.getDate());
    i.setDateCloture(dateClotureChooser.getDate());
    i.setPriorite(cmbPriorite.getSelectedItem().toString());
    i.setStatut(cmbStatut.getSelectedItem().toString());

    Equipement e = (Equipement) cmbEquipement.getSelectedItem();
    Technicien t = (Technicien) cmbTechnicien.getSelectedItem();

    i.setEquipement(e);
    i.setTechnicien(t);

    if (is.update(i)) {
        JOptionPane.showMessageDialog(this,
                "Modification réussie !");
        loadData();
    } else {
        JOptionPane.showMessageDialog(this,
                "Erreur lors de la modification !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed

    int row = Incidents.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un incident à supprimer !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Voulez-vous vraiment supprimer cet incident ?",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {

        int id = Integer.parseInt(model.getValueAt(row, 0).toString());

        Incident i = new Incident();
        i.setIdIncident(id);

        if (is.delete(i)) {
            JOptionPane.showMessageDialog(this,
                    "Suppression réussie !");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de la suppression !",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void cmbPrioriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrioriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrioriteActionPerformed

    private void cmbStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatutActionPerformed

    private void cmbTechnicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTechnicienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTechnicienActionPerformed

    private void cmbEquipementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEquipementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEquipementActionPerformed

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterMouseClicked

    private void IncidentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncidentsMouseClicked
    // TODO add your handling code here:
    int idIncident = Integer.parseInt(model.getValueAt(Incidents.getSelectedRow(), 0).toString());

    dateOuvertureChooser.setDate((Date) model.getValueAt(Incidents.getSelectedRow(), 1));
    dateClotureChooser.setDate((Date) model.getValueAt(Incidents.getSelectedRow(), 2));

    cmbPriorite.setSelectedItem(model.getValueAt(Incidents.getSelectedRow(), 3).toString());
    cmbStatut.setSelectedItem(model.getValueAt(Incidents.getSelectedRow(), 4).toString());

    

    }//GEN-LAST:event_IncidentsMouseClicked
private void loadData() {
    model.setRowCount(0);
    List<Incident> list = is.findAll();
    
    for (Incident i : list) {
        model.addRow(new Object[]{
            i.getIdIncident(),
            i.getDateOuverture(),
            i.getDateCloture(),
            i.getPriorite(),
            i.getStatut(),
            i.getEquipement().getIdEquipement(),   
            i.getTechnicien().getIdTechnicien()    
        });
    }
}
private void loadEquipement() {
    EquipementService es = new EquipementService();
    for (Equipement e : es.findAll()) {
        cmbEquipement.addItem(e);
    }
}

private void loadTechnicien() {
    TechnicienService ts = new TechnicienService();
    for (Technicien t : ts.findAll()) {
        cmbTechnicien.addItem(t);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Incidents;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox cmbEquipement;
    private javax.swing.JComboBox cmbPriorite;
    private javax.swing.JComboBox cmbStatut;
    private javax.swing.JComboBox cmbTechnicien;
    private com.toedter.calendar.JDateChooser dateClotureChooser;
    private com.toedter.calendar.JDateChooser dateOuvertureChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
