/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package incidents.ui;
import incidents.dao.IncidentDaoImpl;
import incidents.entites.Incident;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Date;
import incidents.ui.Rechercheparperiode;
import incidents.service.IncidentService;
import incidents.entites.Incident;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class Rechercheparperiode extends javax.swing.JInternalFrame {
    private IncidentDaoImpl dao = new IncidentDaoImpl();
    private DefaultTableModel model;
    /**
     * Creates new form Rechercheparperiode
     */
   public Rechercheparperiode() {
    initComponents();
    model = (DefaultTableModel) Incidents.getModel();
}
   private void loadByPeriode(Date dateDebut, Date dateFin) {
    model.setRowCount(0);

    List<Incident> list = dao.findByPeriode(dateDebut, dateFin);

    for (Incident i : list) {
        model.addRow(new Object[]{
            i.getIdIncident(),
            i.getPriorite(),
            i.getStatut(),
            i.getEquipement().getIdEquipement(),
            i.getTechnicien().getIdTechnicien()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateOuvertureChooser = new com.toedter.calendar.JDateChooser();
        dateClotureChooser = new com.toedter.calendar.JDateChooser();
        Recherche = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Incidents = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Incidents par periode");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setText("Date d'ouverture:");

        jLabel2.setText("Date Cloture:");

        Recherche.setText("Rechercher");
        Recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateClotureChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOuvertureChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(Recherche)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOuvertureChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dateClotureChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Recherche)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des Incidents "));

        Incidents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Priorite", "Statut", "Equipement", "Technicien"
            }
        ));
        jScrollPane1.setViewportView(Incidents);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercheActionPerformed

    Date dateDebut = dateOuvertureChooser.getDate();
    Date dateFin = dateClotureChooser.getDate();

    // ✅ Vérifier si dates sélectionnées
    if (dateDebut == null || dateFin == null) {
        JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner les deux dates !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ✅ Vérifier période valide
    if (dateDebut.after(dateFin)) {
        JOptionPane.showMessageDialog(this,
                "La date de début doit être avant la date de fin !",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ✅ Appel DAO (utilise celui déjà déclaré en haut)
    List<Incident> list = dao.findByPeriode(dateDebut, dateFin);

    model.setRowCount(0);

    // ✅ Si aucun résultat
    if (list == null || list.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Aucun incident trouvé dans cette période !",
                "Information",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // ✅ Affichage résultats
    for (Incident i : list) {
        model.addRow(new Object[]{
            i.getIdIncident(),
            i.getPriorite(),
            i.getStatut(),
            i.getEquipement().getNom(),
            i.getTechnicien().getNom()
        });
    }

        
    }//GEN-LAST:event_RechercheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Incidents;
    private javax.swing.JButton Recherche;
    private com.toedter.calendar.JDateChooser dateClotureChooser;
    private com.toedter.calendar.JDateChooser dateOuvertureChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
